FROM dataiku/dss
#USER dataiku
#WORKDIR /home/dataiku
#COPY Anaconda2-5.3.1-Linux-x86.sh /home/dataiku/
#RUN /bin/bash /home/dataiku/Anaconda2-5.3.1-Linux-x86.sh -b -p /home/dataiku/conda
#RUN ls -l /home/dataiku/
# RUN rm /home/dataiku/anaconda.sh
#RUN ln -s /home/dataiku/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
#RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
#RUN echo "conda activate base" >> ~/.bashrc
#WORKDIR /
